### ISSUE TITLE
v0.1.9版本bot在新加群后功能失效的BUG及readme文档修改建议

### ISSUE THREAD

**Issue by glamorgan9826** [Reversedeer/nonebot_plugin_eventmonitor#18]
**环境**：python3.10 插件版本v0.1.9
**现象**：bot在新加入一个群后，所有功能，戳一戳等包括开启关闭功能全都失效，群聊无回复，后台日志报错KeyError，只有重启nonebot才正常
**复现方法**：在bot启动状态下新加入群聊，在新群触发功能，指令等
<details> <summary>报错信息</summary>

```
07-26 02:18:52 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=nonebot_plugin_eventmonitor)
07-26 02:18:52 [DEBUG] nonebot | Running Matcher(type='notice', module=nonebot_plugin_eventmonitor)
07-26 02:18:52 [DEBUG] nonebot | Running handler Dependent(call=send_chuo)
07-26 02:18:52 [INFO] nonebot | Matcher(type='notice', module=nonebot_plugin_eventmonitor) running complete
07-26 02:18:52 [ERROR] nonebot | Running Matcher(type='notice', module=nonebot_plugin_eventmonitor) failed.
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\bot_test\bot.py", line 12, in <module>
    nonebot.run()
  File "C:\Users\Admin\PycharmProjects\bot_test\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Admin\PycharmProjects\bot_test\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\Admin\PycharmProjects\bot_test\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "C:\Users\Admin\PycharmProjects\bot_test\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Admin\PycharmProjects\bot_test\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Admin\PycharmProjects\bot_test\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Admin\PycharmProjects\bot_test\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Admin\PycharmProjects\bot_test\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\Users\Admin\PycharmProjects\bot_test\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Admin\PycharmProjects\bot_test\nonebot_plugin_eventmonitor\__init__.py", line 83, in send_chuo
    if not (await check_chuo(g_temp, str(event.group_id))):
  File "C:\Users\Admin\PycharmProjects\bot_test\nonebot_plugin_eventmonitor\utils.py", line 110, in check_chuo
    return g_temp[gid]["chuo"]
KeyError: '548254800'
07-26 02:18:52 [DEBUG] nonebot | Stop event propagation
07-26 02:18:52 [DEBUG] nonebot | Checking for matchers completed
```

</details>

**问题分析**：
g_temp只有在初始化以及触发命令 event配置 时会更新群列表，并且更新在本地文件而不是内存中的g_temp中
这样导致在bot新加入一个群后，内存中的g_temp中仍然不存在该群的gid
然后所有功能在检查是否允许的函数时`check_xxxx(g_temp, gid)`，会访问g_temp中不存在的gid，导致报错，然后功能不执行
选择开启功能，使用的代码是 `g_temp[gid][key] = True` ，也是会直接访问g_temp中不存在的gid赋值，报错，然后开启关闭功能失败
`event配置` 命令的`config_check()`只更新文件，不更新g_temp
最后只有重启bot，走init()初始化重新加载本地文件才能生效
**修改的一种思路**：
如果只是让`config_check()`同时更新内存中的g_temp，在bot加群之后，如果不手动调用`event配置` 命令，还是会报错
可以尝试不通过`bot.get_group_list()`读bot有的群聊，而是每次访问g_temp的时候用`dict.setdefault()`或者手动判断一下gid是否存在，如果访问的gid不存在，直接向dict里写入key为当前gid的记录，比如一个带默认值的字典
**其他问题**：
现在配置文件里的`nickname`又改回必填项了吗？`nickname = next(iter(config.nickname))`不填会报错，如果改回去了的话建议更新下readme中的配置项说明
还有新加入的指令比如`开启/关闭`以及`event配置/event状态`，名称及效果等信息可以加到readme文档和插件的帮助里说明一下喵

**Comment by Reversedeer** [comment]
bot加群后会报错发布前就注意到i了，原本有bot加群后初始化此群，最后又删了（希望用户重启解决问题
 nickname是从env.*里获取NICKNAME=["bot"]，我想这每个人都有填这个配置项,readme就没写。所以您会报错，至于以前没报错，可能是配置文件中有NICKNAME

**Comment by Reversedeer** [comment]
@glamorgan9826 使用dev的版本试试可以用吗

**Comment by glamorgan9826** [comment]
> @glamorgan9826使用dev的版本尝试可以用吗

试了下dev，和之前的效果没有差别，我注意到你在utils.py 里的config_check() 更新了g_temp，用的是=赋值的方式
```
g_temp = config_dict
```
这样好像没法更新到g_temp，可以尝试dict.update()

一个测试，两个文件a.py 和b.py
```
# a.py
from b import *
print(f'调用func()之前的g_temp:  {g_temp}')
func()
print(f'调用func()之后的g_temp:  {g_temp}')
```
```
# b.py
g_temp= {}
def func():
    global g_temp
    g_temp.update({'这个是用': 'update()更新'})
    g_temp = {'这个是用': '='}

```
运行a.py结果是
```
调用func()之前的g_temp:  {}
调用func()之后的g_temp:  {'这个是用': 'update()更新'}
```

================

另外即使用update在config_check()里更新了g_temp，但是在bot加入新群后如果没有显示的使用`event配置`命令或者重启bot的话，触发功能还是会不断报错

**Comment by Reversedeer** [comment]
我本地测试是没有问题的啊

**Comment by Reversedeer** [comment]
有报错就贴出日志来看

**Comment by glamorgan9826** [comment]
> 我本地测试是没有问题的啊 print(g_temp)输出确实是更新后的 看[测试](http://www.duanlian.work/VAQ1D)

首先说明的一点是，我之前提到的所有问题，都是在一个前提下：即在bot新加入一个以前没加入过的群的情况下，才会发生的
至于视频里并没有模拟出bot新加入一个群的状况
视频里的操作，在你删掉硬盘文件config.json里的记录之前，内存中的g_temp已经存在了这个群的记录，你只删掉了硬盘文件里的记录对内存中的g_temp没有影响

matcha模拟新加群的情况可以新建一个群让bot进入，或者想使用已有的群的话，先让bot和可能变成bot的账号退出群，然后停止nonebot程序，再删除硬盘的文件里该群的相关内容，再启动nonebot，然后使用bot加入新群，再把身份切成其他账号进群测试

另外你可以尝试我之前回复里的那个小demo，a.py和b.py那个，使用=赋值的确是不会更新的。至于报错和1楼折叠的内容一样的，都是KeyError，因为新加的群号并不存在于内存中的g_temp，但是被访问了报的错

**Comment by Reversedeer** [comment]
是的，使用直接赋值的方法确实不能更新g_temp
使用g_temp.updata(config_dict)更新后bot新加群会完成初始化并且可以响应所有指令
