### ISSUE TITLE
文档，包名错误，导致一直报错

### ISSUE THREAD

**Issue by mmxd12** [Reversedeer/nonebot_plugin_eventmonitor#27]
`08-07 20:22:32 [ERROR] nonebot | Failed to import "nonebot_plugin_eventmonitor"
Traceback (most recent call last):
  File "/root/wfbot/bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_eventmonitor/__init__.py", line 16, in <module>
    require("nonebot_plugin_apscheduler")
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/load.py", line 188, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_apscheduler"!`
这里存在两个包名"nonebot_plugin_eventmonitor"和"nonebot_plugin_apscheduler"
而且文档有很多写不一样的
![1](https://github.com/user-attachments/assets/6eb96b88-c0fd-42e0-a64c-1f44e368ac11)

**Comment by Reversedeer** [comment]
在pypi中包名是
nonebot-plugin-eventmonitor但在导入插件时必须使用"_"
pip 安装包时无影响
报错主要原因是可能重复导入的两次相同的包，默认安装在site-packages里
使用nb命令安装时会自动在pyproject.py中写入相关信息，使用pip安装需要手动在pyproject.py中添加
如果你将本插件放在/src中则按照readme中的指引完成

**Comment by Reversedeer** [comment]
文档确实有欠缺，后续会改进

**Comment by Reversedeer** [comment]
请问你是否解决了问题呢

**Comment by Reversedeer** [comment]
已更新v0.3.2
